// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RJGHTtbNA2TDjjaL2sN_1sA8qL5tQWg',
    appId: '1:746661776065:web:4abda7cda55d37b4c7e240',
    messagingSenderId: '746661776065',
    projectId: 'wao-app-28d4f',
    authDomain: 'wao-app-28d4f.firebaseapp.com',
    storageBucket: 'wao-app-28d4f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BzbjolKBkPAPGc3rsvAnut4eLmdOa-I',
    appId: '1:633369671789:android:871d7b1bfe4a1f30066764',
    messagingSenderId: '633369671789',
    projectId: 'wao-mobiel-app',
    storageBucket: 'wao-mobiel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtKceb1ePFDG400tjDHZU6eo_8QSVgd1k',
    appId: '1:633369671789:ios:d591337eb07a42a8066764',
    messagingSenderId: '633369671789',
    projectId: 'wao-mobiel-app',
    storageBucket: 'wao-mobiel-app.appspot.com',
    iosClientId: '633369671789-antufu0i6b82i39ohfc5afv49ip4fe8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.waoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3isalGYjfH6U4Y8xmfKy255vK5gpj-Rw',
    appId: '1:746661776065:ios:a9b82a221a912ee5c7e240',
    messagingSenderId: '746661776065',
    projectId: 'wao-app-28d4f',
    storageBucket: 'wao-app-28d4f.firebasestorage.app',
    iosBundleId: 'com.example.waoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4RJGHTtbNA2TDjjaL2sN_1sA8qL5tQWg',
    appId: '1:746661776065:web:97e3ecd681565069c7e240',
    messagingSenderId: '746661776065',
    projectId: 'wao-app-28d4f',
    authDomain: 'wao-app-28d4f.firebaseapp.com',
    storageBucket: 'wao-app-28d4f.firebasestorage.app',
  );

}