// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyz6M1jubojJsWpcbfGY-ZrPtkEnsVCuM',
    appId: '1:556690053319:ios:5279b2cf23d0f764c3c6e2',
    messagingSenderId: '556690053319',
    projectId: 'wao-mobile-app-7e3c9',
    storageBucket: 'wao-mobile-app-7e3c9.firebasestorage.app',
    iosBundleId: 'com.example.waoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpOYdmVLkpI8AQZeFsoMoPQSKpH9zORkg',
    appId: '1:556690053319:web:b1abb8e917915a94c3c6e2',
    messagingSenderId: '556690053319',
    projectId: 'wao-mobile-app-7e3c9',
    authDomain: 'wao-mobile-app-7e3c9.firebaseapp.com',
    storageBucket: 'wao-mobile-app-7e3c9.firebasestorage.app',
  );
}
